version: '3.8' # Specify a standard version

services:
  chroma:
    image: chromadb/chroma:0.5.20 # Updated version with NumPy 2.0 compatibility
    ports:
      - "8000:8000" # Map the default Chroma port 8000 to the host
    volumes:
      - chroma_data:/chroma/.chroma/index # Persist Chroma data using a Docker volume
    environment:
      - ALLOW_RESET=true
      - IS_PERSISTENT=true
      - ANONYMIZED_TELEMETRY=false

volumes:
  chroma_data: # Define the named volume for persistence
    driver: local
